typography_spectrum: 0.11418707622215152
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.7106367615051568
  lightness: 0.41630347701720893
  saturation: 0.07048251130618155
  rhythmicContrast: 0.0034629160072654486
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.974614025792107
analytics:
  google: UA-16623661-1
  facebook: null
  twitter: null
author:
  name: Adrian Evans
  email: adrian@koolapps.com
  url: www.koolapps.com
name: KoolApps
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: KoolApps.com
purpose: []
content: []
github: true
url: 'http://koolapps.co/'
